### PR TITLE
:hammer: fix: fetching both male and female names with data being saved on localstorage with expiry.

### PR DESCRIPTION
**Pull request by anuzpandey**
#3 has been fixed.

Now, only the relevant data are fetched, i.e when user want to fetch the `male` name, only the male names are fetched and loaded to `localstorage` and same is true to `female` names.

Additionally, the `localstorage` items are cached with expiry time of `1 day`.

### CODE REVIEW

**Review by HariAcharya80 — COMMENTED** [review]
This isn't much of a issue, loading few more bytes of data.

**Comment by anuzpandey** [comment]
@HariAcharya80 Current implementation fetch both `male` and `female` names when either of the button are clicked so this was fixed i.e. `:hammer: fix: fetching both male and female names`.

Currently experimenting with this plugin `lazygit` and `title` and `comment` was here and there. I will make the corrections in other commits and pull-requests.

Thank you for the feedback as well.

**Comment by HariAcharya80** [comment]
Ohh got that, what if we fetch both the data once and save both to the localstorage, so that we don't need to fetch for both the `male` and `female` for a certain period of time. Would you mind if I request you to review this ? #4

**Comment by anuzpandey** [comment]
> Ohh got that, what if we fetch both the data once and save both to the localstorage, so that we don't need to fetch for both the `male` and `female` for a certain period of time. Would you mind if I request you to review this ? #4

Hmm.
Why load both at once when we can fetch each separately and save those to localstorage when needed, with this idea I created this commit #2.

Example:
If user wants to get Male name only why bother loading female names onto the storage.

**Pull request merged**
