### PR TITLE
:sparkles: updates: the tech stach from vanilla js to vue-vite and ts

### PR DESCRIPTION
**Pull request by anuzpandey**
Changes:
- Application stack updated from `vanilla-js` to `Vue3`.
- Pinia and other required dependencies are installed for future use.
- Application now utilize the proper folder structure.

### CODE REVIEW

**Review by HariAcharya80 — APPROVED** [review]
Seems fine

**Comment by HariAcharya80** [comment]
@anuzpandey I think will have the current deployment to fail?

**Comment by anuzpandey** [comment]
> @anuzpandey I think will have the current deployment to fail?

Yes the current deployment will fail as the vite output directory is set to `dist` by default, so, @rbcrossley needs to update the github page settings.

Lets do the basic integration first on the local environment and we will deploy the application through vercel.
Or if things goes smoothly we can buy a domain and add it to it.

**Comment by HariAcharya80** [comment]
Cool was thinking the same :)

**Pull request merged**
